version: '3'

services:
  web:
    build: ./api/
    tty: true
    volumes:
      - .:/go/src
    ports:
      - 3030:3030
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    ports:
     - 3306:3306
    env_file:
      - ./mysql/.env
    command: --default-authentication-plugin=mysql_native_password

 