version: '3'

services:
  web:
    build: ./api
    tty: true
    volumes:
      - ./api:/go/src
    ports:
      - 3030:3000
    depends_on:
      - db

  db:
    image: mysql:8
    ports:
     - 3306:3306
    command: --default-authentication-plugin=mysql_native_password